

FILE_LIST = zip/add.c \
			zip/add_dir.c \
			zip/close.c \
			zip/delete.c \
			zip/dirent.c \
			zip/entry_free.c \
			zip/entry_new.c \
			zip/err_str.c \
			zip/error.c \
			zip/error_clear.c \
			zip/error_get.c \
			zip/error_get_sys_type.c \
			zip/error_strerror.c \
			zip/error_to_str.c \
			zip/fclose.c \
			zip/file_error_clear.c \
			zip/file_error_get.c \
			zip/file_get_offset.c \
			zip/file_strerror.c \
			zip/filerange_crc.c \
			zip/fopen.c \
			zip/fopen_index.c \
			zip/fread.c \
			zip/free.c \
			zip/get_archive_comment.c \
			zip/get_archive_flag.c \
			zip/get_file_comment.c \
			zip/get_num_files.c \
			zip/get_name.c \
			zip/memdup.c \
			zip/name_locate.c \
			zip/new.c \
			zip/open.c \
			zip/rename.c \
			zip/replace.c \
			zip/set_archive_comment.c \
			zip/set_archive_flag.c \
			zip/set_file_comment.c \
			zip/source_buffer.c \
			zip/source_file.c \
			zip/source_filep.c \
			zip/source_free.c \
			zip/source_function.c \
			zip/source_zip.c \
			zip/set_name.c \
			zip/stat.c \
			zip/stat_index.c \
			zip/stat_init.c \
			zip/strerror.c \
			zip/unchange.c \
			zip/unchange_all.c \
			zip/unchange_archive.c \
			zip/unchange_data.c